# Generated by Django 3.2.16 on 2023-04-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230422_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['following']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='foiiowing',
            new_name='following',
        ),
    ]
